## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("data/WeatherPy_vacation.csv")
vacation_df.head(15)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Tuktoyaktuk,CA,-31.00,clear sky,69.4541,-133.0374,End of The Road Ltd.
1,1,Brandfort,ZA,72.81,broken clouds,-28.7001,26.4597,SUMFRA GUESTHOUSE
2,2,Hobart,AU,60.03,overcast clouds,-42.8794,147.3294,Mantra on Collins Hobart
3,3,Domoni,KM,79.81,light rain,-12.2569,44.5319,Al Djadid
4,4,Avarua,CK,77.05,scattered clouds,-21.2078,-159.7750,Paradise Inn
5,5,Bluff,NZ,50.11,scattered clouds,-46.6000,168.3333,Bluff Homestead - Guesthouse & Campervan Park
6,6,Muros,ES,61.23,clear sky,42.7762,-9.0603,Apartment Av. Castelao
7,7,Mahebourg,MU,80.89,scattered clouds,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
8,8,Namatanai,PG,79.95,broken clouds,-3.6667,152.4333,Seagulls Inn Namatani
9,9,Rikitea,PF,78.62,broken clouds,-23.1203,-134.9692,People ThankYou
10,10,Sistranda,NO,33.76,broken clouds,63.7256,8.8340,Hotell Frøya
11,11,Busselton,AU,68.04,clear sky,-33.6500,115.3333,Observatory Guest House
12,12,Ushuaia,AR,60.46,scattered clouds,-54.8000,-68.3000,Albatross Hotel
13,13,Westport,US,29.32,scattered clouds,41.1415,-73.3579,The Westport Inn
14,14,Tawang,IN,15.24,scattered clouds,27.5833,91.8667,Hotel Mount View

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>

"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp],
                                 dissipating=False,
                                 max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.
vacation_start = vacation_df.loc[vacation_df['City'] == 'Hasaki']
vacation_end = vacation_df.loc[vacation_df['City'] == 'Hasaki']
vacation_stop1 = vacation_df.loc[vacation_df['City'] == 'Komatsu']
vacation_stop2 = vacation_df.loc[vacation_df['City'] == 'Shimoda'] 
vacation_stop3 = vacation_df.loc[vacation_df['City'] == 'Katsuura']

In [6]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start["Lat"].to_numpy(), vacation_start["Lng"].to_numpy()
end = vacation_end["Lat"].to_numpy(), vacation_end["Lng"].to_numpy()
stop1 = vacation_stop1["Lat"].to_numpy(), vacation_stop1["Lng"].to_numpy()
stop2 = vacation_stop2["Lat"].to_numpy(), vacation_stop2["Lng"].to_numpy()
stop3 = vacation_stop3["Lat"].to_numpy(), vacation_stop3["Lng"].to_numpy()

In [7]:
import gmaps.datasets

In [8]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
hasaki = (35.7333, 140.8333)
komatsu = (36.4026, 136.4509)
shimoda = (34.6667, 138.95)
katsuura = (35.1333, 140.3)

fig = gmaps.figure()
city_itinerary = gmaps.directions_layer(
        hasaki, hasaki, waypoints=[komatsu, shimoda, katsuura],
        travel_mode='DRIVING')

fig.add_layer(city_itinerary)
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
city1 = vacation_df.loc[vacation_df['City'] == 'Hasaki']
city2 = vacation_df.loc[vacation_df['City'] == 'Komatsu']
city3 = vacation_df.loc[vacation_df['City'] == 'Shimoda']
city4 = vacation_df.loc[vacation_df['City'] == 'Katsuura']

In [10]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([city1, city2, city3, city4], ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,274,Hasaki,JP,27.00,broken clouds,35.7333,140.8333,Hotel Sunrise Choshi
1,700,Komatsu,JP,32.25,overcast clouds,36.4026,136.4509,APAHOTEL KOMATSU GRAND
2,253,Shimoda,JP,34.11,clear sky,34.6667,138.9500,Shimoda Tokyu Hotel
3,58,Katsuura,JP,33.91,broken clouds,35.1333,140.3000,Katsuura Hotel Mikazuki

In [11]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map.
locations = itinerary_df[["Lat", "Lng"]]
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp],
                                 dissipating=False,
                                 max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))